// ========================================
// EXAMPLES OF GENERATED FILES
// ========================================

/**
 * This file shows examples of what each generator produces.
 * These are actual outputs from running the plop-next generators.
 */

// ========================================
// 1. React Component Generator Output
// ========================================

// File: generated/components/DatePicker/DatePicker.tsx
// Template: component.tsx.hbs
// Prompts: componentName=DatePicker, description="A date selection component", etc.

/*
/**
 * DatePicker Component
 * 
 * Auto-generated by plop-next at 2026-03-26 14:30
 */

import React, { FC, ReactNode } from 'react';
import styles from './DatePicker.module.scss';

export interface DatePickerProps {
  title?: string;
  disabled?: boolean;
  children?: ReactNode;
  onAction?: () => void;
}

export const DatePicker: FC<DatePickerProps> = ({
  title = "DatePicker",
  disabled = false,
  children,
  onAction,
}) => {
  return (
    <div className={styles.container} data-testid="date-picker">
      <div className={styles.header}>
        <h2 className={styles.title}>{title}</h2>
      </div>
      <div className={styles.content}>
        {children}
      </div>
      {onAction && (
        <button
          className={styles.button}
          disabled={disabled}
          onClick={onAction}
          data-testid="date-picker-action-button"
        >
          Trigger Action
        </button>
      )}
    </div>
  );
};
*/

// File: generated/components/DatePicker/index.ts
// Template: inline template
// Output:
/*
/**
 * DatePicker - Export file
 * Generated at: 2026-03-26 14:30
 */

export { DatePicker, type DatePickerProps } from './DatePicker';
export type * from './DatePicker';
*/

// File: generated/components/DatePicker/README.md
// Template: inline template with data formatting
// Output:
/*
# DatePicker

**Description:** A date selection component

**Type:** FORM

**Author:** Dev Team

**Generated:** 2026-03-26 14:30

## Usage

```tsx
import { DatePicker } from './DatePicker';

export function App() {
  return (
    <DatePicker 
      title="DatePicker Title"
      onAction={() => console.log('Action triggered!')}
    >
      Your content here
    </DatePicker>
  );
}
```

## Props

- `title` (string): The component title
- `disabled` (boolean): Disable the action button
- `children` (ReactNode): Content to display
- `onAction` (function): Callback when action is triggered

## Type
This is a **form** component.

### Storybook
📖 [View in Storybook](https://storybook.example.com/date-picker)

## Tests
Run tests with: `npm test -- DatePicker.test.tsx`
*/

// ========================================
// 2. TypeScript Utility Generator Output
// ========================================

// File: generated/utils/format-date.ts
// Template: util.ts.hbs with conditionals
// Prompts: utilityName=formatDate, inputType=Date, returnType=string, includeTypes=true, etc.

/*
/**
 * formatDate Utility
 * 
 * Auto-generated by plop-next
 * Category: formatting
 * Description: Format a date to ISO string with time
 */

export interface FormatDateOptions {
  verbose?: boolean;
}

export function formatDate(
  input: Date,
  options?: FormatDateOptions
): string {
  const { verbose = false } = options ?? {};

  if (verbose) {
    console.log(`[formatDate] Processing:`, input);
  }

  // TODO: Implement formatDate logic
  
  return input as string;
}

export async function formatDateAsync(
  input: Date,
  options?: FormatDateOptions
): Promise<string> {
  // Simulate async work
  await new Promise((resolve) => setTimeout(resolve, 0));
  return formatDate(input, options);
}

export function validateFormatDateInput(input: unknown): input is Date {
  return typeof input === 'string' || typeof input === 'object';
}
*/

// File: generated/utils/format-date.test.ts
// Template: inline template with {{#if}} and {{#each}}
// Output:
/*
/**
 * Tests for formatDate
 * Category: formatting
 * Auto-generated by plop-next
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { formatDate, formatDateAsync, validateFormatDateInput } from './format-date';

describe('formatDate (formatting)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('basic functionality', () => {
    it('should be a function', () => {
      expect(typeof formatDate).toBe('function');
    });

    it('should accept Date input', () => {
      const input: Date = null as unknown as Date;
      expect(() => formatDate(input)).not.toThrow();
    });

    it('should return string', () => {
      const result = formatDate(null as unknown as Date);
      expect(result).toBeDefined();
    });
  });

  describe('async version', () => {
    it('should have async variant', () => {
      expect(typeof formatDateAsync).toBe('function');
    });

    it('should return a promise', async () => {
      const result = formatDateAsync(null as unknown as Date);
      expect(result).toBeInstanceOf(Promise);
    });
  });

  describe('validation', () => {
    it('should validate input', () => {
      const isValid = validateFormatDateInput(null);
      expect(typeof isValid).toBe('boolean');
    });
  });
});
*/

// ========================================
// 3. Backend Service Generator Output
// ========================================

// File: generated/services/user-service/userService.service.ts
// Template: service.ts.hbs
// Shows generated service class with methods

/*
/**
 * UserService Service
 * 
 * Auto-generated by plop-next
 * Feature: authentication
 * Description: Handle user authentication and account management
 * Environment: production
 * Version: 1.0.0
 */

export interface UserServiceConfig {
  baseUrl: string;
  timeout?: number;
  retryAttempts?: number;
}

export interface UserServiceResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  timestamp: Date;
}

export class UserService {
  private config: UserServiceConfig;
  private isInitialized = false;

  constructor(config: UserServiceConfig) {
    this.config = {
      timeout: 5000,
      retryAttempts: 3,
      ...config,
    };
  }

  async init(): Promise<void> {
    if (this.isInitialized) {
      return;
    }

    console.log(`Initializing UserService with baseUrl: ${this.config.baseUrl}`);
    
    this.isInitialized = true;
  }

  // Methods generated from template...
  // (Implements retry logic, error handling, etc.)

  dispose(): void {
    this.isInitialized = false;
    console.log(`UserService disposed`);
  }
}

export function createUserService(
  config: UserServiceConfig,
): UserService {
  return new UserService(config);
}
*/

// File: generated/services/user-service/config.ts
// Template: inline template with environment-based config
// Output:
/*
/**
 * Configuration for UserService Service
 * Environment: PRODUCTION
 * Feature: authentication
 * Generated: 2026-03-26 14:30
 */

const environments = {
  development: {
    baseUrl: 'http://localhost:3000/api',
    timeout: 10000,
    retryAttempts: 3,
  },
  staging: {
    baseUrl: 'https://staging-api.example.com',
    timeout: 8000,
    retryAttempts: 2,
  },
  production: {
    baseUrl: 'https://api.example.com',
    timeout: 5000,
    retryAttempts: 1,
  },
};

export const userServiceConfig = environments['production' as keyof typeof environments];

export const SERVICE_METADATA = {
  name: 'UserService',
  environment: 'PRODUCTION',
  feature: 'authentication',
  version: '1.0.0',
  createdAt: new Date('2026-03-26 14:30'),
} as const;
*/

// ========================================
// 4. Demo All Prompts Output
// ========================================

// File: generated/demo/project-config.json
// Template: inline with name transformations and loops
// Prompts: projectName=my-awesome-project, features=[typescript, eslint, prettier], etc.

/*
{
  "name": "my-awesome-project",
  "displayName": "MyAwesomeProject",
  "camelName": "myAwesomeProject",
  "snakeName": "my_awesome_project",
  "generateTests": true,
  "packageManager": "npm",
  "features": ["typescript", "eslint", "prettier"],
  "featureCount": 3,
  "generatedAt": "2026-03-26 14:30",
  "metdata": {
    "environment": "development",
    "version": "1.0.0"
  }
}
*/

// File: generated/demo/README.md
// Template: inline with conditionals and loops
// Output:
/*
# MyAwesomeProject Demo

## Project Details

- **Name**: my-awesome-project
- **Package Manager**: npm
- **Generate Tests**: Yes ✅
- **Generated At**: 2026-03-26 14:30

## Name Transformations

my-awesome-project gets transformed as:
- **PascalCase**: MyAwesomeProject
- **camelCase**: myAwesomeProject
- **kebab-case**: my-awesome-project
- **snake_case**: my_awesome_project

## Features Included

Selected features (3 total):
- ✓ typescript
- ✓ eslint
- ✓ prettier

## Test Generation

Test files will be generated for all modules.
Run: `npm test`

---

This file was auto-generated by plop-next comprehensive demo.
*/

// ========================================
// 5. Test File Generator Output
// ========================================

// File: generated/tests/authentication.test.ts
// Template: inline with conditional framework logic
// Prompts: testName=authentication, testFramework=vitest, testTypes=[unit, integration]

/*
/**
 * Authentication Test Suite
 * 
 * Framework: VITEST
 * Author: QA Team
 * Generated: 2026-03-26 14:30
 * Types: unit, integration
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';

describe('Authentication', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('unit', () => {
    it('should be implemented', () => {
      expect(true).toBe(true);
    });
  });

  describe('integration', () => {
    it('should be implemented', () => {
      expect(true).toBe(true);
    });
  });
});
*/

// ========================================
// KEY TAKEAWAYS
// ========================================

/**
 * HELPERS USED IN GENERATION:
 * 
 * 1. pascalCase: MyComponent, DatePicker, UserService
 * 2. camelCase: myComponent, datePicker, userService
 * 3. kebabCase: my-component, date-picker, user-service
 * 4. snakeCase: my_component, date_picker, user_service
 * 5. upper: PRODUCTION, FORM, VITEST
 * 6. lower: production, form, vitest
 * 7. now: 2026-03-26 14:30 (current timestamp)
 * 8. joinArray: combine array elements with separator
 * 9. eq: equality comparison for conditionals
 * 
 * TEMPLATES:
 * - component.tsx.hbs       → React component with JSX
 * - component.test.ts.hbs   → Full test suite with fixtures
 * - component.module.scss.hbs → Responsive SCSS styles
 * - util.ts.hbs             → TypeScript utility with types
 * - service.ts.hbs          → Service class with retry logic
 * - Inline templates        → Config, README, index files
 * 
 * FEATURES:
 * - {{#if condition}} conditional rendering
 * - {{#each array}} iteration over arrays
 * - {{this}} current item reference
 * - {{#unless}} inverse condition
 * - Partial helpers with sub-field access
 */
