import { styleText } from "node:util";
import figures from "figures";

const spinnerFrames = [
  "1         ",
  " 1        ",
  "  1       ",
  "   1      ",
  "    1     ",
  "     1    ",
  "      1   ",
  "       1  ",
  "        1 ",
  "         1",
  "         2",
  "        2 ",
  "       2  ",
  "      2   ",
  "     2    ",
  "    2     ",
  "   2      ",
  "  2       ",
  " 2        ",
  "2         ",
  "3         ",
  " 3        ",
  "  3       ",
  "   3      ",
  "    3     ",
  "     3    ",
  "      3   ",
  "       3  ",
  "        3 ",
  "         3",
  "         4",
  "        4 ",
  "       4  ",
  "      4   ",
  "     4    ",
  "    4     ",
  "   4      ",
  "  4       ",
  " 4        ",
  "4         ",
  "5         ",
  " 5        ",
  "  5       ",
  "   5      ",
  "    5     ",
  "     5    ",
  "      5   ",
  "       5  ",
  "        5 ",
  "         5",
  "         6",
  "        6 ",
  "       6  ",
  "      6   ",
  "     6    ",
  "    6     ",
  "   6      ",
  "  6       ",
  " 6        ",
  "6         ",
  "7         ",
  " 7        ",
  "  7       ",
  "   7      ",
  "    7     ",
  "     7    ",
  "      7   ",
  "       7  ",
  "        7 ",
  "         7",
  "         8",
  "        8 ",
  "       8  ",
  "      8   ",
  "     8    ",
  "    8     ",
  "   8      ",
  "  8       ",
  " 8        ",
  "8         ",
  "9         ",
  " 9        ",
  "  9       ",
  "   9      ",
  "    9     ",
  "     9    ",
  "      9   ",
  "       9  ",
  "        9 ",
  "         9",
  "         0",
  "        0 ",
  "       0  ",
  "      0   ",
  "     0    ",
  "    0     ",
  "   0      ",
  "  0       ",
  " 0        ",
  "0         ",
].map((frame) => styleText("blue", frame));

const Theme = {
  prefix: {
    idle: styleText("blue", figures.questionMarkPrefix),
    done: styleText("green", figures.tick),
  },
  spinner: {
    interval: 100,
    frames: spinnerFrames,
  },
  style: {
    answer: (text: string) => styleText("magenta", text),
    message: (text: string) => styleText(["bold", "white"], text),
    error: (text: string) => styleText(["redBright", "underline"], `> ${text}`),
    defaultAnswer: (text: string) => styleText("green", `(${text})`),
    help: (text: string) => styleText(["italic", "cyan"], text),
    highlight: (text: string) => styleText("yellow", text),
    key: (text: string) => styleText(["yellow", "bold"], `<${text}>`),
    waitingMessage: (enterKey: string) =>
      styleText("gray", `Press ${enterKey} to launch your preferred editor.`),
    maskedText: styleText("gray", "[input is masked]"),
  },
  generatorList: {
    style: {
      highlight: (text: string) => styleText(["bold", "blue"], text),
      description: (text: string) => styleText("blue", text),
    },
  },
  i18n: {
    disabledError: "This option is disabled and cannot be selected.",
  },
  plopNext: {
    welcome: (text: string) => styleText(["bold", "magenta"], text),
    generatorMenu: {
      title: (text: string) => {
        return styleText(["bold", "blue"], text);
      },
      description: (text: string) => {
        return styleText("blue", text);
      },
    },
    actionLog: {
      success: (text: string) => styleText("yellow", `+ ${text}`),
      skipped: (text: string) => styleText("magenta", `- ${text}`),
      info: (text: string) => styleText("white", text),
    },
    errors: {
      prefix: {
        error: styleText(["bold", "red"], "ERR"),
        warning: styleText(["bold", "yellow"], "WARN"),
      },
      error: (text: string) => styleText(["bold", "red"], text),
      warning: (text: string) => styleText(["bold", "yellow"], text),
    },
  },
};

export default Theme;
